pipeline {
    agent any

    environment {
        IMAGE_NAME = "mongo-init-image"
    }

    stages {
        stage('Build Docker Image') {
            steps {
                sh "docker build -t $IMAGE_NAME:${BUILD_NUMBER} -f mongodb/Dockerfile mongodb/"
            }
        }
    }
}