pipeline {
    agent any

    environment {
        IMAGE_NAME = "mongo-init-image"
    }

    stages {

        stage('Clone Repository') {
            steps {
                git 'https://github.com/veenay910/Roboshop-Docker.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t $IMAGE_NAME:${BUILD_NUMBER} ."
            }
        }
    }
}